package:
  name: gamma-sklearndf
  version: 1.0.0

source:
  git_url: {{FACET_PATH}}/sklearndf/

build:
  noarch: python
  script: "python -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python={{ environ.get('FACET_V_PYTHON_BUILD', '3.8') }}
  run:
    - python>=3.6,<4
    - pandas{{ environ.get('FACET_V_PANDAS', '>=0.24') }}
    - numpy{{ environ.get('FACET_V_NUMPY', '>=1.16') }}
    - scikit-learn{{ environ.get('FACET_V_SKLEARN', '>=0.22') }}
    - boruta_py{{ environ.get('FACET_V_BORUTA', '>=0.3') }}
    - pyyaml=5
    - lightgbm{{ environ.get('FACET_V_LGBM', '>=2.2') }}
    - gamma-pytools
test:
  imports:
    - sklearndf
    - sklearndf.classification
    - sklearndf.classification.extra
    - sklearndf.pipeline
    - sklearndf.regression
    - sklearndf.regression.extra
    - sklearndf.transformation
    - sklearndf.transformation.extra
  requires:
    - pytest=5.2
  commands:
    - python -c 'import sklearndf;
                 import os;
                 assert sklearndf.__version__ == os.environ["PKG_VERSION"]'